# don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

function prompt {
  local st=$?
  if [ $st -eq 0 ]; then
    st=
  else
    st='! '
  fi
  local wd=$(pwd)
  if [ "$wd" = "$HOME" ]; then
    wd='~'
  else
    wd=$(basename "$wd")
  fi
  local branch=$(git rev-parse --abbrev-ref HEAD 2>/dev/null)
  if [[ $branch = *[![:space:]]* ]]; then
    branch=" ᛘ $branch"
    if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
      branch="${branch}*"
    fi
  else
    branch=
  fi
  echo -n "${st}${wd}${branch} \$ "
}
PS1='\[\e[34m\e[1m\]$(prompt)\[\e[0m\]'

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors -a -n "$color_prompt" ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    #alias dir='dir --color=auto'
    #alias vdir='vdir --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

alias gist='git status'
alias girc='GIT_EDITOR=true git rebase --continue'
alias gitlog='git log --format="%h %s"'
alias bn=build-notify
alias gica='git commit -a --amend --no-edit'
alias gibr='git rev-parse --abbrev-ref HEAD'

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

export EDITOR='emacsclient -c'
export DOTNET_CLI_TELEMETRY_OPTOUT=true

function bb {
  pushd . &>/dev/null
  while [ $(pwd) != / -a ! -d blaze-bin -a ! -d bazel-bin ]; do
    cd ..
  done
  if [ -d blaze-bin -o -d bazel-bin ]; then
    echo $(pwd)
  else
    echo "blaze-bin-parent-does-not-exist"
  fi
  popd &>/dev/null
}

function build-notify {
  if [ $? -eq 0 ]; then
    notify-send -i weather-clear 'Success!' 'Build completed.'
  else
    notify-send -i weather-showers 'Failed!' 'Build completed.'
  fi
}

function go-local-workspace {
  if [ -e WORKSPACE ]; then
    echo "WORKSPACE already exists" >&1
    return 1
  fi
  cat >WORKSPACE <<EOF
local_repository(
    name = "io_bazel_rules_go",
    path = "$HOME/Code/rules_go",
)

load("@io_bazel_rules_go//go:deps.bzl", "go_rules_dependencies", "go_register_toolchains")

go_rules_dependencies()

go_register_toolchains()

local_repository(
    name = "bazel_gazelle",
    path = "$HOME/Code/bazel-gazelle",
)

load("@bazel_gazelle//:deps.bzl", "gazelle_dependencies")

gazelle_dependencies()
EOF
  cat >BUILD.bazel <<EOF
load("@bazel_gazelle//:def.bzl", "gazelle")
load("@io_bazel_rules_go//go:def.bzl", "go_binary", "go_library")

# gazelle:prefix example.com/hello
gazelle(name = "gazelle")

go_binary(
    name = "hello",
    embed = [":go_default_library"],
    visibility = ["//visibility:public"],
)

go_library(
    name = "go_default_library",
    srcs = ["hello.go"],
    importpath = "example.com/hello",
    visibility = ["//visibility:public"],
)
EOF
  cat >hello.go <<EOF
package main

import "fmt"

func main() {
	fmt.Println("Hello, world!")
}
EOF
}

function install-bazel {
  if [ $# -ne 1 ]; then
    echo "usage: install-bazel version" >&1
    return 1
  fi
  local version=$1
  if [ "$version" = HEAD ]; then
    local ci_base="http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=linux-x86_64/lastSuccessfulBuild/artifact/output/ci"
    local ci_artifact=$(wget -qO- ${ci_base} | grep -o 'bazel-[^\"]*-installer.sh' | uniq)
    local url="$ci_base/$ci_artifact"
  else
    local url="https://github.com/bazelbuild/bazel/releases/download/$version/bazel-$version-installer-linux-x86_64.sh"
  fi
  local download=$HOME/Downloads/install.sh
  wget -O "$download" "$url"
  chmod +x "$download"
  "$download" --user
  rm -f "$download"
  if [ -e ~/.bazelrc.bak ]; then
    mv ~/.bazelrc.bak ~/.bazelrc
  fi
  hash -d bazel
}

function install-go {
  if [ $# -ne 1 ]; then
    echo "usage: install-go version" >&1
    return 1
  fi
  local version=$1
  local goos=
  if [ "$(uname)" = Darwin ]; then
    goos=darwin
  else
    goos=linux
  fi
  local url=https://dl.google.com/go/$version.$goos-amd64.tar.gz
  local download=$HOME/Downloads/go-downloads/$version.$goos-amd64.tar.gz
  local install=/opt/go/$version
  if [ ! -d "$install" ]; then
    if [ ! -e "$download" ]; then
      mkdir -p "$(dirname "$download")"
      curl -L --output "$download" "$url"
    fi
    tar xf "$download" -C "$(dirname "$download")"
    mv "$(dirname "$download")/go" "$install"
  fi
  rm /opt/go/installed
  ln -sf "$install" /opt/go/installed
}

function rm-bazel {
  if [ -d bazel-out ]; then
    bazel clean
  fi
  if [ ! -f WORKSPACE ]; then
    echo "no workspace file; are you at the repo root?" >&2
    return 1
  fi
  rm -f WORKSPACE
  find . -name BUILD -o -name BUILD.bazel -delete
}

function cdgo {
  cd "$GOPATH/src/$1"
}

function wake {
  case "$1" in
  karst)
    wol -a 192.168.1.255:9 -t 4c:ed:fb:94:39:06
    ;;
  *)
    echo "unknown host $1" >&2
    return 1
    ;;
  esac
}

function hush {
  case "$1" in
  karst)
    ssh jay@karst.localdomain sudo systemctl suspend
    ;;
  *)
    echo "unknown host $1" >&2
    return 1
    ;;
  esac
}

function find-in {
  find . -type f -name "$2" -exec grep -Hn "$1" {} \;
}

function git-clean-branch {
  local branch
  local mergeBase
  local tree
  local squashed
  local main=$(git rev-parse --abbrev-ref origin/HEAD | sed s,origin/,,)
  git for-each-ref refs/heads --format="%(refname:short)" | while read branch; do
    if [ "$branch" == "$main" ]; then
      continue
    fi
    mergeBase=$(git merge-base $main "$branch")
    if [ $? -ne 0 ]; then
      continue
    fi
    tree=$(git rev-parse "$branch^{tree}")
    if [ $? -ne 0 ]; then
      continue
    fi
    squashed=$(git commit-tree "$tree" -p "$mergeBase" -m _)
    if [ $? -ne 0 ]; then
      continue
    fi
    if ! git cherry "$squashed" | grep -qv '^-'; then
      git branch -D "$branch"
    fi
  done
}

function gotestenv {
  export GOMODCACHE=~/Code/modcache
  go clean -modcache
  export GOPROXY=http://localhost:6123/mod
  export GOSUMDB=off
  PATH=~/goroot/bin:$DEFAULT_PATH
  if [ $# -eq 1 ]; then
    local name=$1
    txtar -x <"$(go env GOROOT)/src/cmd/go/testdata/script/${name}.txt"
  fi
}

alias bn=build-notify
alias gica='git commit -a --amend --no-edit'
alias gibr='git rev-parse --abbrev-ref HEAD'
